[General]
**.routingRecorder.enabled = false

############### Statistics ##################
output-scalar-file = ${resultdir}/${configname}/${ue}-${scheduler}.sca
output-vector-file = ${resultdir}/${configname}/${ue}-${scheduler}.vec

**.scalar-recording = true
**.vector-recording = true

**.sctp.**.scalar-recording = false  # remove annoying statistics from SCTP
**.sctp.**.vector-recording = false  # remove annoying statistics from SCTP



#**.meanBitLifeTimePerPacket*.vector-recording = true
#**.avgServedBlocksUl*.vector-recording = true
#**.packetReceived*.vector-recording = true
#**.packetSent*.vector-recording = true
#**.packetSent*.scalar-recording = true
#**.packetReceived*.scalar-recording = true


############### SCTP configuration ##################
**.sctp.nagleEnabled = false         # if true, transmission of small packets will be delayed on the X2
**.sctp.enableHeartbeats = false

################ Mobility parameters #####################

**.mobility.constraintAreaMaxX = 1000m
**.mobility.constraintAreaMaxY = 1000m
**.mobility.constraintAreaMinX = 0m
**.mobility.constraintAreaMinY = 0m
**.mobility.constraintAreaMinZ = 0m
**.mobility.constraintAreaMaxZ = 0m
**.mobility.initFromDisplayString = false


*.numUe = ${ue=1,2,5,10,20,25,30,50,80}

**.mac.schedulingDiscipline* = ${scheduler="QOS_PF", "LYAPUNOV_SCHEDULER"}#, "PF", "ALLOCATOR_BESTFIT", "MAXCI_COMP", "MAXCI"

**.mac.lyAlpha = 1.5 #1.5
**.mac.lyBeta = 1.2 #1.2
 
############### Transmission Power ##################
**.ueTxPower = 23dBm
**.eNodeBTxPower = 24dBm
**.targetBler = 0.01
**.blerShift = 5


**.downlinkInterference = true
**.uplinkInterference = true


############### IPv4 configurator config #################
*.configurator.config = xmldoc("./demo.xml")


############## Component carrier
*.carrierAggregation.numComponentCarriers = 1
*.carrierAggregation.componentCarrier[0].numBands = 51 #Number of Resource Blocks - equal to the number of RBs -
#Ref : 20 MHz Channel Bandwidth : 51, 40 MHz Channel Bandwidth: 106 - All with Sub-carrier spacing (kHz) 30 (Numerology 1)
*.carrierAggregation.componentCarrier[0].numerologyIndex = 1
*.carrierAggregation.componentCarrier[0].carrierFrequency = 5.9GHz ##5.9



*.gnb*.cellularNic.numCarriers = 1
*.gnb*.cellularNic.channelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"
*.ue[*].cellularNic.numCarriers = 1
*.ue[*].cellularNic.nrChannelModel[0].componentCarrierModule = "carrierAggregation.componentCarrier[0]"


############### Indoor Factory Profile #################
#INDOOR_FACTORY_SL - Sparse clutter, Low BS /.d_clutter = 10m /.clutter_density_r =0.39 #lower than 0.4 /.hClutter = 10m
#INDOOR_FACTORY_DL - Dense clutter, Low BS /.d_clutter = 2m /.clutter_density_r = 0.4 #greater than 0.4 /.hClutter = 5m
#INDOOR_FACTORY_SH - Sparse clutter, High BS /.d_clutter = 10m /.clutter_density_r = 0.39 #lower than 0.4 / .hClutter = 10 #m lower than ceilingHeight (0-10)
#INDOOR_FACTORY_DH - Dense clutter, High BS / .d_clutter = 2m / .clutter_density_r = 0.4 #greater than 0.4 / .hClutter = 10m
#INDOOR_FACTORY_HH - high Tx, high Rx / .d_clutter = 10m /.clutter_density_r = 0.39 / .hClutter = 15m
**.channelModel.scenario = ${scenario="INDOOR_FACTORY_SL"} #, "INDOOR_FACTORY_DL", "INDOOR_FACTORY_SH", "INDOOR_FACTORY_DH"


**.channelModel.d_clutter = 10m
**.channelModel.clutter_density_r = 0.39
**.channelModel.hClutter = 10m

**.dynamic_los= true

#------------------------------------#
# Config Standalone
#
# Topology configuration for the exemplary scenario for NR Standalone deployment
#
[Config Standalone]
network = simu5g.simulations.Kouros.MultigNB.MultiCell_Standalone
sim-time-limit=100s
warmup-period = 20s


# --- B. gNB Positions ---
# Placed 400m apart to create an interference zone in the middle
*.gnb1.mobility.initialX = 300m
*.gnb1.mobility.initialY = 500m
*.gnb2.mobility.initialX = 700m
*.gnb2.mobility.initialY = 500m
*.gnb*.cellularNic.sdap.qfiContextFile = "qfi_drb_mapping_config.txt"
*.gnb*.cellularNic.numDrbs = 7
*.gnb*.cellularNic.mac.amcType = "NrAmc"


############### X2 configuration #################
*.gnb*.numX2Apps = 1                                        # one x2App per peering node
*.gnb*.x2App[*].server.localPort = 5000 + ancestorIndex(1)  # Server ports (x2App[0]=5000, x2App[1]=5001, ...)
*.gnb1.x2App[0].client.connectAddress = "gnb2%x2ppp0"
*.gnb2.x2App[0].client.connectAddress = "gnb1%x2ppp0"

############## UE configuration ##################
# Force gNB1 to be Cell ID 1
*.gnb1.cellularNic.mac.cellId = 1
*.gnb1.cellularNic.phy.cellId = 1

# Force gNB2 to be Cell ID 2
*.gnb2.cellularNic.mac.cellId = 2
*.gnb2.cellularNic.phy.cellId = 2

*.ue[*].cellularNic.sdap.qfiContextFile = "qfi_drb_mapping_config.txt"
*.ue[*].cellularNic.numDrbs = 7



# connect the UE's NIC to the corresponding serving gNB (NR side only)
# 1. DISABLE Dynamic Association
# We want to force the scenario. If true, UEs might switch back to gNB1 if it's slightly stronger.
**.dynamicCellAssociation = false
**.enableHandover = false

# 2. GROUP 1: UEs 0-9 -> Force to gNB1
*.ue[0..9].macCellId = 1
*.ue[0..9].masterId = 1
*.ue[0..9].nrMacCellId = 1   # <--- CRITICAL FOR 5G
*.ue[0..9].nrMasterId = 1    # <--- CRITICAL FOR 5G

# Mobility: Left side (Near gNB1)
*.ue[0..9].mobility.typename = "LinearMobility"
*.ue[0..9].mobility.initialX = uniform(250m, 450m) 
*.ue[0..9].mobility.initialY = uniform(400m, 600m)


# 3. GROUP 2: UEs 10+ -> Force to gNB2
# Note: Using "ue[10..]" applies to 10, 11, ... up to numUe.
*.ue[10..].macCellId = 2
*.ue[10..].masterId = 2
*.ue[10..].nrMacCellId = 2   # <--- CHANGED FROM 1 TO 2
*.ue[10..].nrMasterId = 2    # <--- CHANGED FROM 1 TO 2

# Mobility: Right side (Near gNB2)
*.ue[10..].mobility.typename = "LinearMobility"
*.ue[10..].mobility.initialX = uniform(550m, 750m)
*.ue[10..].mobility.initialY = uniform(400m, 600m)



#------------------------------------#
# Buffer size - 200KB
#*.ue[*].cellularNic.nrRlc[*].**.queueSize=204800B
#*.ue[*].cellularNic.nrMac.queueSize = 204800B
############### TEMP OFF*.ue[*].cellularNic.nrMac.queueSize = 20480B
#*.ue[*].cellularNic.rlc.*.queueSize = 204800B
#*.ue[*].cellularNic.mac.queueSize=204800B
############### TEMP OFF*.ue[*].cellularNic.mac.queueSize=20480B

#*.gnb.cellularNic.nrRlc[*].**.queueSize=204800B
#*.gnb.cellularNic.nrMac.queueSize = 204800B
############### TEMP OFF*.gnb.cellularNic.nrMac.queueSize = 20480B
#*.gnb.cellularNic.rlc.*.queueSize = 204800B
#*.gnb.cellularNic.mac.queueSize=204800B
############### TEMP OFF*.gnb.cellularNic.mac.queueSize=20480B




#------------------------------------#
# Config VoIP-DL
#
# General configuration for Voice-over-IP DL traffic to the UE
#
[Config UDP-DL]
extends=Standalone

# multiple UDP applications for each UE
*.ue[*].numApps = 3

# the amount of UDP applications on server should be equal to (numUEs)*(ue[*].numApps)
*.server.numApps = 3

#============= Application Setup =============
*.ue[*].app[*].typename = "UdpSinkApp"

# Configure each sink to listen on its designated port.
*.ue[*].app[0].display-name = "vehicle control "
*.ue[*].app[0].io.localPort = 1000

*.ue[*].app[1].display-name = "video"
*.ue[*].app[1].io.localPort = 1001

*.ue[*].app[2].display-name = "best effort"
*.ue[*].app[2].io.localPort = 1002


#============= Server Setup (Sender) =============
# The server has three source applications, one for each traffic type.
*.server.app[*].typename = "UdpSourceApp"

# --- Server App 0: Vehicle Control ---
*.server.app[0].display-name = "vehicle control"
*.server.app[0].io.destAddress = "ue[0]"  # Sends traffic to all UEs
*.server.app[0].io.destPort = 1000
*.server.app[0].source.packetLength = 150B
*.server.app[0].source.productionInterval = intuniform(44ms, 45ms)
*.server.app[0].source.qfi = 3

# --- Server App 1: Video ---
*.server.app[1].display-name = "video source"
*.server.app[1].io.destAddress = "ue[0]"
*.server.app[1].io.destPort = 1001
*.server.app[1].source.packetLength = int(200B + bernoulli(0.05) * 1000B)
*.server.app[1].source.productionInterval = 33.3ms
*.server.app[1].source.qfi = 5

# --- Server App 2: Best Effort ---
*.server.app[2].display-name = "BestEffort source"
*.server.app[2].io.destAddress = "ue[0]"
*.server.app[2].io.destPort = 1002
*.server.app[2].source.packetLength = int(64B + bernoulli(0.3) * 1386B)
*.server.app[2].source.productionInterval = pareto_shifted(1.2, 12ms, 1ms)
*.server.app[2].source.qfi = 7

# --- Common Timing for Server Apps ---
*.server.app[*].startTime = uniform(0s,0.02s)
*.server.app[*].source.initialProductionOffset = uniform(0ms, 5ms)

#------------------------------------#



#------------------------------------#
# Config VoIP-UL
#
# General configuration for Voice-over-IP UL traffic from the UE
#
[Config UDP-UL]
extends=Standalone


**.uplink_interference = true
############## Scheduler configuration ##################

# multiple UDP applications for each UE
*.ue[*].numApps = 3

# the amount of UDP applications on server should be equal to (numUEs)*(ue[*].numApps)
*.server.numApps = 3

#============= Application Setup =============
*.server.app[*].typename = "UdpSinkApp"
*.server.app[0].display-name = "vehicle control"
*.server.app[0].io.localPort = 1000
*.server.app[1].display-name = "video"
*.server.app[1].io.localPort = 1001
*.server.app[2].display-name = "best effort"
*.server.app[2].io.localPort = 1002

*.ue[*].app[0].typename = "UdpSourceApp"
*.ue[*].app[0].display-name = "vehicle control"
*.ue[*].app[0].io.destAddress = "server"
*.ue[*].app[0].io.destPort = 1000
*.ue[*].app[0].source.packetLength = 150B
*.ue[*].app[0].source.productionInterval = intuniform(44ms, 45ms)



*.ue[*].app[1].typename = "UdpSourceApp"
*.ue[*].app[1].display-name = "video"
*.ue[*].app[1].io.destAddress = "server"
*.ue[*].app[1].io.destPort = 1001
# --- 30 FPS Video Stream---
# This expression creates a bimodal distribution:
# - 95% of packets will be 200B (small P/B-frames)
# - 5% of packets will be 1200B (large I-frames)
#*.ue[*].app[1].source.packetLength = int(200B + bernoulli(0.05) * 1000B)
#*.ue[*].app[1].source.packetLength = int(200B + bernoulli(0.05) * 1000B)
# Packet interval is fixed to match a 30 FPS camera
*.ue[*].app[1].source.productionInterval = 33.333ms

##Prof.Cormac values
# --- target: 4 Mb/s per AGV  at ~30 fps ---
# (5% ⇒ 0.05 * 30fps = 1.5 I-frames/sec → satisfies "not less than 1/sec")
#*.ue[*].app[1].source.packetLength = (bernoulli(0.05) == 1) ? int(uniform(50000B, 60000B)) : int(truncnormal(14385B, 2000B))
*.ue[*].app[1].source.packetLength = (bernoulli(0.05) == 1) ? int(uniform(50000B, 60000B)) : int(uniform(12400B, 16400B))



# --- 60 FPS Video Stream (using intuniform) ---
# Packet interval is fixed to match a 60 FPS camera (1s / 60)
#*.ue[*].app[1].source.productionInterval = 16.7ms
#*.ue[*].app[1].source.packetLength = intuniform(150B, 1450B)


# Packet size is a random integer between 200 and 1450 bytes.
# Covers P/B-frames and larger I-frames.
#*.ue[*].app[1].source.packetLength = intuniform(200, 1450)*1B
##########

*.ue[*].app[2].typename = "UdpSourceApp"
*.ue[*].app[2].display-name = "BestEffort"
*.ue[*].app[2].io.destAddress = "server"
*.ue[*].app[2].io.destPort = 1002
*.ue[*].app[2].source.packetLength = int(64B + bernoulli(0.3) * 1386B)
*.ue[*].app[2].source.productionInterval = pareto_shifted(1.2, 50ms, 20ms)



*.ue[*].app[0].source.qfi = 4
*.ue[*].app[1].source.qfi = 5
*.ue[*].app[2].source.qfi = 7

*.ue[*].app[*].source.initialProductionOffset = uniform(0s, 2s)
*.ue[*].app[*].startTime = uniform(0s,0.05s)     